_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 41
                - 55
                - 80
            "2":
                - 1
                - 41
                - 55
                - 80
            "3":
                - 1
                - 17
                - 23
                - 55
                - 61
                - 62
            "4": 3.8.20
            "5": 0.19.1
            "8":
                - 5
                - 9
            "12": 0.19.1
            "13": linux-x86_64
